[workspace]
resolver = "2"
members = [
    "crates/prism-core",
    "crates/prism-bench",
    "crates/prism-python",
]

[workspace.package]
version = "0.3.0"
edition = "2021"
rust-version = "1.80"
license = "Apache-2.0"
authors = ["Yuriy Peysakhov"]
repository = "https://github.com/yp3y5akh0v/prism"

[workspace.dependencies]
rand = "0.8"
rayon = "1.10"
byteorder = "1.5"
memmap2 = "0.9"
zeroize = ">=1.7, <1.9"
pyo3 = { version = "0.29.2" }
numpy = "0.29.0"
